# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: "3.5"

# Define services
services:
  # App Service
  app:
    # Configuration for building the docker image for the service
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: unless-stopped
    environment: # Pass environment variables to the service
      DB_HOST: terraform-20250411194126172200000001.cg6cp6bnc2ao.eu-north-1.rds.amazonaws.com
      DB_PORT: 5432
      API_PORT: 80
      DB_USER: postgres
      DB_PASSWORD: secretpassword
      DB_NAME: armadacms
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
    volumes:
      - .:/app
      - /app/frontend/dist # preserve the Docker-built frontend, don't overwrite with host

networks:
  backend:
