# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

# Define services
services:
  # App Service
  app:
    # Configuration for building the docker image for the service
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: unless-stopped
    env_file:
      - .env
    environment: # Pass environment variables to the service
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: ${DB_SSLMODE}
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

networks:
  backend:
